name:                parallelism-and-concurency-training

dependencies:
- base >= 4.7 && < 5
- parallel
- deepseq
- split

ghc-options:
- -Wall
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  app:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - parallelism-and-concurency-training
